const encounterPokemon = [
    {
        pokemonName: "Infernape",
        gif: "infernape",
        shiny: "infernapeshiny",
        backgif: "",
        shinyback: "",
        level: "50",
        curHP: 200,
        maxHP: 200,
        type: ["Fire", "Fighting"],
        moves: {
            moveID: "Fire Punch",
            dmg: 50,
            type: ["Fire"],
        },
    },
    {
        pokemonName: "Blastoise",
        gif: "blastoise",
        shiny: "blastoiseshiny",
        backgif: "",
        shinyback: "",
        level: "50",
        curHP: 250,
        maxHP: 250,
        type: ["Water"],
        moves: {
            moveID: "Surf",
            dmg: 60,
            type: ["Water"],
        },
    },
    {
        pokemonName: "Milotic",
        gif: "milotic",
        shiny: "miloticshiny",
        backgif: "",
        shinyback: "",
        level: "50",
        curHP: 260,
        maxHP: 260,
        type: ["Water"],
        moves: {
            moveID: "Hydro Pump",
            dmg: 120,
            type: ["Water"],
        },
    },
    {
        pokemonName: "Zoroark",
        gif: "zoroark",
        shiny: "zoroarkshiny",
        backgif: "",
        shinyback: "",
        level: "50",
        curHP: 238,
        maxHP: 238,
        type: ["Dark"],
        moves: {
            moveID: "Feint",
            dmg: 40,
            type: ["Dark"],
        },
    },
    {
        pokemonName: "Golurk",
        gif: "golurk",
        shiny: "golurkshiny",
        backgif: "",
        shinyback: "",
        level: "50",
        curHP: 301,
        maxHP: 301,
        type: ["Ghost", "steel"],
        moves: {
            moveID: "Shadow Ball",
            dmg: 60,
            type: ["Ghost"],
        },
    },
]

const yourPokemon = [
    {
        pokemonName: "Genesect",
        gif: "genesect",
        shiny: "genesectshiny",
        backgif: "genesectback",
        shinyback: "genesectshinyback",
        level: "79",
        curHP: 250,
        maxHP: 250,
        type: ["Bug", "Steel"],
        moves: {
            moveID: "X-Scissor",
            dmg: 60,
            type: ["Bug"],
        },
    },
]

const battlePokemon = [
    {
        pokemonName: "",
        gif: "",
        shiny: "",
        backgif: "",
        shinyback: "",
        level: "",
        curHP: 250,
        maxHP: 250,
        type: [""],
        moves: {
            moveID: "",
            dmg: 60,
            type: [""],
        },
    },
]