const encounterPokemon = [
    {
        pokemonName: "Infernape",
        gif: "infernape",
        shiny: false,
        level: 50,
        curHP: 200,
        maxHP: 200,
        baseHP: 200,
        healthGrowth: 5,
        type: ["Fire", "Fighting"],
        moves: {
            moveID: "Fire Punch",
            dmg: 50,
            type: ["Fire"],
        },
    },
    {
        pokemonName: "Blastoise",
        gif: "blastoise",
        shiny: false,
        level: 50,
        curHP: 250,
        maxHP: 250,
        baseHP: 250,
        healthGrowth: 2,
        type: ["Water"],
        moves: {
            moveID: "Surf",
            dmg: 60,
            type: ["Water"],
        },
    },
    {
        pokemonName: "Milotic",
        gif: "milotic",
        shiny: false,
        level: 50,
        curHP: 260,
        maxHP: 260,
        baseHP: 260,
        healthGrowth: 2,
        type: ["Water"],
        moves: {
            moveID: "Hydro Pump",
            dmg: 120,
            type: ["Water"],
        },
    },
    {
        pokemonName: "Zoroark",
        gif: "zoroark",
        shiny: false,
        level: 50,
        curHP: 238,
        maxHP: 238,
        baseHP: 238,
        healthGrowth: 4,
        type: ["Dark"],
        moves: {
            moveID: "Feint",
            dmg: 40,
            type: ["Dark"],
        },
    },
    {
        pokemonName: "Golurk",
        gif: "golurk",
        shiny: false,
        level: 50,
        curHP: 301,
        maxHP: 301,
        baseHP: 301,
        healthGrowth: 7,
        type: ["Ghost", "steel"],
        moves: {
            moveID: "Shadow Ball",
            dmg: 60,
            type: ["Ghost"],
        },
    },
]

const yourPokemon = [
    {
        pokemonName: "Genesect",
        gif: "genesect",
        shiny: true,
        level: 79,
        curHP: 327,
        maxHP: 327,
        baseHP: 327,
        healthGrowth: 16,
        type: ["Bug", "Steel"],
        moves: {
            moveID: "X-Scissor",
            dmg: 60,
            type: ["Bug"],
        },
    },
]

const battlePokemon = [
    {
        pokemonName: "",
        gif: "",
        shiny: false,
        level: 0,
        curHP: 250,
        maxHP: 250,
        baseHP: 250,
        healthGrowth: 0,
        type: [""],
        moves: {
            moveID: "",
            dmg: 60,
            type: [""],
        },
    },
]