const encounterPokemon = [
    {
        pokemonName: "Infernape",
        gif: "infernape",
        shiny: false,
        level: 50,
        curHP: 200,
        maxHP: 200,
        baseHP: 200,
        healthGrowth: 5,
        type: ["Fire", "Fighting"],
        moves: {
            moveID: "Fire Punch",
            dmg: 50,
            type: "Fire",
        },
    },
    {
        pokemonName: "Blastoise",
        gif: "blastoise",
        shiny: false,
        level: 50,
        curHP: 250,
        maxHP: 250,
        baseHP: 250,
        healthGrowth: 2,
        type: ["Water"],
        moves: {
            moveID: "Surf",
            dmg: 60,
            type: "Water",
        },
    },
    {
        pokemonName: "Milotic",
        gif: "milotic",
        shiny: false,
        level: 50,
        curHP: 260,
        maxHP: 260,
        baseHP: 260,
        healthGrowth: 2,
        type: ["Water"],
        moves: {
            moveID: "Hydro Pump",
            dmg: 120,
            type: "Water",
        },
    },
    {
        pokemonName: "Zoroark",
        gif: "zoroark",
        shiny: false,
        level: 50,
        curHP: 238,
        maxHP: 238,
        baseHP: 238,
        healthGrowth: 4,
        type: ["Dark"],
        moves: {
            moveID: "Feint",
            dmg: 40,
            type: "Dark",
        },
    },
    {
        pokemonName: "Golurk",
        gif: "golurk",
        shiny: false,
        level: 50,
        curHP: 301,
        maxHP: 301,
        baseHP: 301,
        healthGrowth: 7,
        type: ["Ghost", "steel"],
        moves: {
            moveID: "Shadow Ball",
            dmg: 60,
            type: "Ghost",
        },
    },
    {
        pokemonName: "Chandelure",
        gif: "chandelure",
        shiny: false,
        level: 50,
        curHP: 250,
        maxHP: 250,
        baseHP: 250,
        healthGrowth: 2,
        type: ["Ghost", "Fire"],
        moves: {
            moveID: "Shadow Ball",
            dmg: 60,
            type: "Ghost",
        },
    },
    {
        pokemonName: "Charizard",
        gif: "charizard",
        shiny: false,
        level: 50,
        curHP: 300,
        maxHP: 300,
        baseHP: 300,
        healthGrowth: 2,
        type: ["Fire", "Flying"],
        moves: {
            moveID: "Flamethrower",
            dmg: 70,
            type: "Fire",
        },
    },
    {
        pokemonName: "Garchomp",
        gif: "garchomp",
        shiny: false,
        level: 50,
        curHP: 325,
        maxHP: 325,
        baseHP: 325,
        healthGrowth: 3,
        type: ["Dragon", "Ground"],
        moves: {
            moveID: "Dragon Claw",
            dmg: 90,
            type: "Dragon",
        },
    },
    {
        pokemonName: "Mienshao",
        gif: "mienshao",
        shiny: false,
        level: 50,
        curHP: 250,
        maxHP: 250,
        baseHP: 250,
        healthGrowth: 1,
        type: ["Normal"],
        moves: {
            moveID: "Head Butt",
            dmg: 35,
            type: "Normal",
        },
    },
    {
        pokemonName: "Muk",
        gif: "muk",
        shiny: false,
        level: 50,
        curHP: 290,
        maxHP: 290,
        baseHP: 290,
        healthGrowth: 3,
        type: ["Poison"],
        moves: {
            moveID: "Sludge Bomb",
            dmg: 60,
            type: "Poison",
        },
    },
    {
        pokemonName: "Munchlax",
        gif: "munchlax",
        shiny: false,
        level: 20,
        curHP: 150,
        maxHP: 150,
        baseHP: 150,
        healthGrowth: 2,
        type: ["Normal"],
        moves: {
            moveID: "Scratch",
            dmg: 30,
            type: "Normal",
        },
    },
    {
        pokemonName: "Pikachu",
        gif: "pikachu",
        shiny: false,
        level: 50,
        curHP: 200,
        maxHP: 200,
        baseHP: 200,
        healthGrowth: 1,
        type: ["Electric"],
        moves: {
            moveID: "Thunderbolt",
            dmg: 75,
            type: "Electric",
        },
    },
    {
        pokemonName: "Rotom-Wash",
        gif: "rotomwash",
        shiny: false,
        level: 50,
        curHP: 250,
        maxHP: 250,
        baseHP: 250,
        healthGrowth: 1,
        type: ["Ghost", "Water"],
        moves: {
            moveID: "Hydro Pump",
            dmg: 120,
            type: "Water",
        },
    },
    {
        pokemonName: "Snorlax",
        gif: "snorlax",
        shiny: false,
        level: 50,
        curHP: 300,
        maxHP: 300,
        baseHP: 300,
        healthGrowth: 3,
        type: ["Normal"],
        moves: {
            moveID: "Giga Impact",
            dmg: 120,
            type: "Normal",
        },
    },
    {
        pokemonName: "Staraptor",
        gif: "staraptor",
        shiny: false,
        level: 50,
        curHP: 180,
        maxHP: 180,
        baseHP: 180,
        healthGrowth: 2,
        type: ["Normal", "Flying"],
        moves: {
            moveID: "Brave Bird",
            dmg: 78,
            type: "Flying",
        },
    },
    {
        pokemonName: "Venusaur",
        gif: "venusaur",
        shiny: false,
        level: 50,
        curHP: 250,
        maxHP: 250,
        baseHP: 250,
        healthGrowth: 2,
        type: ["Normal", "Poison"],
        moves: {
            moveID: "Solar Beam",
            dmg: 80,
            type: "Grass",
        },
    },
    {
        pokemonName: "Zekrom",
        gif: "zekrom",
        shiny: false,
        level: 50,
        curHP: 250,
        maxHP: 250,
        baseHP: 250,
        healthGrowth: 2,
        type: ["Dragon", "Electric"],
        moves: {
            moveID: "Thunder",
            dmg: 80,
            type: "Electric",
        },
    },
]

const yourPokemon = [
    {
        pokemonName: "Genesect",
        gif: "genesect",
        shiny: true,
        level: 79,
        curHP: 327,
        maxHP: 327,
        baseHP: 327,
        healthGrowth: 16,
        type: ["Bug", "Steel"],
        moves: {
            moveID: "X-Scissor",
            dmg: 60,
            type: "Bug",
        },
    }
]

const battlePokemon = [
    {
        pokemonName: "",
        gif: "",
        shiny: false,
        level: 0,
        curHP: 250,
        maxHP: 250,
        baseHP: 250,
        healthGrowth: 0,
        type: [""],
        moves: {
            moveID: "",
            dmg: 60,
            type: "",
        },
    },
]


let jeffery = [

]

let santaClaus = [
    
]

let greg = [
    
]